name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Color filters test
      id: color-filters-test
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Color filters test
        setup-command: pip install -r requirements.txt
        command: python -m pytest
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COLOR-FILTERS-TEST_RESULTS: "${{steps.color-filters-test.outputs.result}}"
      with:
        runners: color-filters-test
